# Generated by Django 3.1.7 on 2021-04-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210411_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='uid',
            new_name='id',
        ),
    ]
