# Generated by Django 3.1.7 on 2021-04-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210411_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='blog_comment',
            new_name='comment',
        ),
    ]
